.TH "CORTINA" "1" "June 13, 2010" "Eric Baudach" ""
.SH "NAME"
Cortina \- a desktop wallpaper management application for the GNOME desktop
.SH "DESCRIPTION"
This manual page documents briefly the
.B cortina
command.
.PP 
\fBCortina\fP completes (or replaces) the built\-in GNOME desktop wallpapers selection tool.
Cortina changes wallpapers by time. 
It works as an tray application with an configuration interface and 
works great under Ubuntu Lucid and all other  GNOME using distributions.
.SH "OPTIONS"
cortina 
.SH "SEE ALSO"
cortina home page: https://launchpad.net/cortina/

The GNU General Public License.
.SH "AUTHOR"
cortina was written by Eric Baudach <Eric.Baudach@web.de>.
.PP 
This manual page was written by Eric Baudach <Eric.Baudach@web.de>.
