#############################################################################
# Makefile for building: fondos-bicentenario
# Generated by qmake (2.01a) (Qt 4.6.3) on: mié sep 18 14:54:13 2013
# Project:  Fondos-Bicentenario.pro
# Template: app
# Command: /usr/bin/qmake -nocache -unix QMAKE_CFLAGS_RELEASE=-g\ -O2 QMAKE_CXXFLAGS_RELEASE=-g\ -O2 QMAKE_LFLAGS_RELEASE=-Wl,-Bsymbolic-functions QMAKE_STRIP=: PREFIX=/usr -o Makefile Fondos-Bicentenario.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -O2 -D_REENTRANT -DORBIT2=1 -pthread -I/usr/include/gconf/2 -I/usr/include/orbit-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -pthread -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -O2 -D_REENTRANT -DORBIT2=1 -pthread -I/usr/include/gconf/2 -I/usr/include/orbit-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -pthread -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-Bsymbolic-functions
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtNetwork -lQtCore -lpthread -lgconf-2 -pthread -lgobject-2.0 -lgthread-2.0 -lrt -lglib-2.0 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = :
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		threadb.cpp \
		widget.cpp \
		helper.cpp moc_widget.cpp \
		moc_threadb.cpp \
		moc_helper.cpp \
		qrc_rc.cpp
OBJECTS       = main.o \
		threadb.o \
		widget.o \
		helper.o \
		moc_widget.o \
		moc_threadb.o \
		moc_helper.o \
		qrc_rc.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Fondos-Bicentenario.pro
QMAKE_TARGET  = fondos-bicentenario
DESTDIR       = 
TARGET        = fondos-bicentenario

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_widget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Fondos-Bicentenario.pro /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -nocache -unix QMAKE_CFLAGS_RELEASE=-g\ -O2 QMAKE_CXXFLAGS_RELEASE=-g\ -O2 QMAKE_LFLAGS_RELEASE=-Wl,-Bsymbolic-functions QMAKE_STRIP=: PREFIX=/usr -o Makefile Fondos-Bicentenario.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -nocache -unix QMAKE_CFLAGS_RELEASE=-g\ -O2 QMAKE_CXXFLAGS_RELEASE=-g\ -O2 QMAKE_LFLAGS_RELEASE=-Wl,-Bsymbolic-functions QMAKE_STRIP=: PREFIX=/usr -o Makefile Fondos-Bicentenario.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/fondos-bicentenario1.0.0 || $(MKDIR) .tmp/fondos-bicentenario1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/fondos-bicentenario1.0.0/ && $(COPY_FILE) --parents widget.h threadb.h helper.h .tmp/fondos-bicentenario1.0.0/ && $(COPY_FILE) --parents rc.qrc .tmp/fondos-bicentenario1.0.0/ && $(COPY_FILE) --parents main.cpp threadb.cpp widget.cpp helper.cpp .tmp/fondos-bicentenario1.0.0/ && $(COPY_FILE) --parents widget.ui .tmp/fondos-bicentenario1.0.0/ && $(COPY_FILE) --parents po/ca.ts po/cs.ts po/de.ts po/es.ts po/fa.ts po/fi.ts po/fr.ts po/ia.ts po/it.ts po/kk.ts po/ko.ts po/nl.ts po/pl.ts po/pt_BR.ts po/pt.ts po/ru.ts po/si.ts po/sv.ts po/th.ts po/tr.ts po/uk.ts po/zh_CN.ts .tmp/fondos-bicentenario1.0.0/ && (cd `dirname .tmp/fondos-bicentenario1.0.0` && $(TAR) fondos-bicentenario1.0.0.tar fondos-bicentenario1.0.0 && $(COMPRESS) fondos-bicentenario1.0.0.tar) && $(MOVE) `dirname .tmp/fondos-bicentenario1.0.0`/fondos-bicentenario1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/fondos-bicentenario1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_widget.cpp moc_threadb.cpp moc_helper.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_widget.cpp moc_threadb.cpp moc_helper.cpp
moc_widget.cpp: ui_widget.h \
		threadb.h \
		widget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) widget.h -o moc_widget.cpp

moc_threadb.cpp: threadb.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) threadb.h -o moc_threadb.cpp

moc_helper.cpp: helper.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) helper.h -o moc_helper.cpp

compiler_rcc_make_all: qrc_rc.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_rc.cpp
qrc_rc.cpp: rc.qrc \
		logo.jpg \
		fondos-bicentenario.png \
		list-remove.png \
		fondos-bicentenario2.png \
		list-add.png
	/usr/bin/rcc -name rc rc.qrc -o qrc_rc.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_widget.h
ui_widget.h: widget.ui
	/usr/bin/uic-qt4 widget.ui -o ui_widget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp widget.h \
		ui_widget.h \
		threadb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

threadb.o: threadb.cpp threadb.h \
		widget.h \
		ui_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o threadb.o threadb.cpp

widget.o: widget.cpp widget.h \
		ui_widget.h \
		threadb.h \
		helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

helper.o: helper.cpp helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o helper.o helper.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

moc_threadb.o: moc_threadb.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_threadb.o moc_threadb.cpp

moc_helper.o: moc_helper.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_helper.o moc_helper.cpp

qrc_rc.o: qrc_rc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_rc.o qrc_rc.cpp

####### Install

install_background: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/fondos-bicentenario/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/fondos-bicentenario/ 
	-$(INSTALL_DIR) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/backgrounds $(INSTALL_ROOT)/usr/share/fondos-bicentenario/
	-$(INSTALL_DIR) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/res $(INSTALL_ROOT)/usr/share/fondos-bicentenario/


uninstall_background:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/fondos-bicentenario/backgrounds 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/fondos-bicentenario/res
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/fondos-bicentenario/ 


install_icon: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/pixmaps/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/pixmaps/ 
	-$(INSTALL_FILE) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/fondos-bicentenario.png $(INSTALL_ROOT)/usr/share/pixmaps/
	-$(INSTALL_FILE) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/fondos-bicentenario2.png $(INSTALL_ROOT)/usr/share/pixmaps/


uninstall_icon:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/pixmaps/fondos-bicentenario.png 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/pixmaps/fondos-bicentenario2.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/pixmaps/ 


install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install_desktop: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/applications/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/applications/ 
	-$(INSTALL_FILE) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/fondos-bicentenario.desktop $(INSTALL_ROOT)/usr/share/applications/


uninstall_desktop:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/fondos-bicentenario.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_languages: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/ 
	$(QTDIR)lrelease -silent Fondos-Bicentenario.pro


install_translations: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/ 
	-$(INSTALL_FILE) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/po/ca.qm $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/
	-$(INSTALL_FILE) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/po/cs.qm $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/
	-$(INSTALL_FILE) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/po/de.qm $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/
	-$(INSTALL_FILE) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/po/es.qm $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/
	-$(INSTALL_FILE) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/po/fa.qm $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/
	-$(INSTALL_FILE) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/po/fi.qm $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/
	-$(INSTALL_FILE) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/po/fr.qm $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/
	-$(INSTALL_FILE) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/po/ia.qm $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/
	-$(INSTALL_FILE) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/po/it.qm $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/
	-$(INSTALL_FILE) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/po/kk.qm $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/
	-$(INSTALL_FILE) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/po/ko.qm $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/
	-$(INSTALL_FILE) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/po/nl.qm $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/
	-$(INSTALL_FILE) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/po/pl.qm $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/
	-$(INSTALL_FILE) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/po/pt.qm $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/
	-$(INSTALL_FILE) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/po/pt_BR.qm $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/
	-$(INSTALL_FILE) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/po/ru.qm $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/
	-$(INSTALL_FILE) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/po/si.qm $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/
	-$(INSTALL_FILE) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/po/sv.qm $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/
	-$(INSTALL_FILE) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/po/th.qm $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/
	-$(INSTALL_FILE) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/po/tr.qm $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/
	-$(INSTALL_FILE) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/po/uk.qm $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/
	-$(INSTALL_FILE) /home/jquintero/Documentos/Proyectos\ Cenditel/Salvapantallas/svn_source/salvapantallas/fondos-bicentenario-0.1/po/zh_CN.qm $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/


uninstall_translations:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/ca.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/cs.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/de.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/es.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/fa.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/fi.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/fr.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/ia.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/it.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/kk.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/ko.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/nl.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/pl.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/pt.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/pt_BR.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/ru.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/si.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/sv.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/th.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/tr.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/uk.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/zh_CN.qm
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/qt4/translations/fondos-bicentenario/ 


install:  install_background install_icon install_target install_desktop install_languages install_translations  FORCE

uninstall: uninstall_background uninstall_icon uninstall_target uninstall_desktop uninstall_translations   FORCE

FORCE:

